### ISSUE TITLE
Introduce more sophisticated examples 

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [thma/PolysemyCleanArchitecture#3]
This article was a pleasure to read, but as for a beginner I am it left some questions unanswered. I understand that this article is not an ultimate guide to haskell, but still I hope for some clarification on these cases.

1. Where data validation should be implemented? Does one provide smart constructors which return Validation type or it should be done in use cases layer and domain layer itself left only to work on valid data?
2. Some computations are better handled by the database engine. Say, we want to get all historical reservations by one person, maybe ordered by date or size of reservation. Of course this could be done purely, but database engines provide their capabilities for performing such actions and in some cases they may be more performant. Is this the price we pay for using this architecture or a there implementations for that? Also when database grows too big you probably don't want to load a whole table into memory, only a specific section of it. How does one implements data structure for such sectioning of data?
3. How to apply multiple interfaces to same use cases? Say, I want a REST API but also a WebSockets server running simultaneously and sharing the same state. But also additional interfaces should be completely optional and for an app to function at least one has to be provided.

While this may sound somewhat offtopic, I personally think these are general questions, answers to which may help build an understanding of whole idea and some intuition on applying it.

**Comment by thma** [comment]
Hi, thanks for your interest in my article!

You are right, the article is not a meant as a comprehensive introduction to Haskell, domain driven design, clean architecture and polysemy. I'm just trying to explain how an algebraic effect system like polysemy can be used to implement a close to ideal clean architecture. Of course I'm not covering all the nitty gritty details.

Regarding your questions:
1. Validation is typically done across several (if not all) layers:
- Directly in the front end you'll validate simple syntactic errors (e.g. date formats)
- In the domain layer you can to domain validation typically handled by smart constructors (as you suggest)
- in the use case layer you do complex cross-domain validation. That is on the use case layer you can interact with data from different independent bounded contexts (e.g. "Customer" and "Contract"). You can validate customer and contract data with smart constructors of their domains. But in order to validate if a contract fits to a customer you'll have to validate both entities in conjunction  (and this typically also involves cross-cutting business logic).

2. It's totally possible to handle expensive queries in the DB and access those queries by providing dedicated effects (and their respective implementations). 

That said, I can understand your unease, as my example is not a classic bottom-up design where you start with an ER model in the database and build the higher levels on top of that.

When designing the domain layer I tried to model the actual domain entities from a user perspective and tried to keep the model clean of any 'persistence artifacts' (like technical keys, foreign keys, finders, ORM hints, etc.) This kind of model fits nicely to key/values stores or document oriented databases.

Of course you might model your data more closely to a traditional entity/relationship based model which fits better to a relational DB.

3. The use case layer handles the state of the data model. Adding aditional interfaces on the outer layers is the natural approach in clean architecture (aka. Onion architecture). A few days ago I added a few lines of code that allow to run a warp based rest service as an effect. In the same way it would be possible to run additional interfaces as effects in parallel. See also: 
https://github.com/thma/PolysemyCleanArchitecture/issues/2#issuecomment-1167558793

**Comment by Sakuya-Izayoi** [comment]
Thanks for your answer!
